name: Publish Tagged Version

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/tags\//}


      - uses: actions/checkout@main
      - name: Build & Publish FE to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: galaxyfuture/comandx
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: latest,${{ steps.get_version.outputs.SOURCE_TAG }}

